### ISSUE TITLE
Theme Options Issues after WP 3.6 - aggregated

### ISSUE THREAD

**Issue by vothsco** [cuny-academic-commons/cbox-theme#170]
As requested by Matt and Boone - here are some reported issues related to theme options since WP upgrade, but (I think) after the CBOX fix:

"my theme options deliver a blank page with a 0 in the top left hand corner, so I am unable to alter logos, favicons etc"

http://commonsinabox.org/groups/help-support/forum/topic/theme-options

" At first, the options page didn’t load correctly (the edit setting and documentation tabs merged into one long page) and I would get the “loading option editor” notice at the top with the loading graphic, but it would just keep spinning. I figured out that if I went to another tab such as user docs or dev docs, then the options page would load correctly. However, I still cannot upload a logo. I just click and it does nothing. Any ideas?"

http://commonsinabox.org/groups/help-support/forum/topic/theme-options-issues/

"I also cannot really change the cbox theme options, when clicking on them some sort of error message appears at the top of the screen but it is just a blank red box with a red cross"

http://commonsinabox.org/groups/help-support/forum/topic/errors-after-installing-the-cbox-theme/

**Comment by r-a-y** [comment]
See #224.
