### ISSUE TITLE
Undefined offset: 2 in cbox-theme/engine/ICE/components/options/component.php on line 552

### ISSUE THREAD

**Issue by JonathanReeve** [cuny-academic-commons/cbox-theme#215]
Received this message in `wp-content/debug.log`: 

    [07-Aug-2014 19:41:39 UTC] PHP Notice:  Undefined offset: 2 in /vagrant/app/public/wp-content/themes/cbox-theme/engine/ICE/components/options/component.php on line 552

**Comment by r-a-y** [comment]
I've noticed a ton of warnings as well.

I don't want to touch too much of the CBOX Theme internals as they are subject to change in Infinity.  I would recommend posting this upstream instead:
https://github.com/PressCrew/infinity/issues

In the meantime, I am suppressing warnings for CBOX Theme and various other plugins with this:
https://gist.github.com/r-a-y/bab85fc47fa0357a8100

**Comment by JonathanReeve** [comment]
Good point. This looks like an Infinity issue. So many of the PHP complaints I see in the error logs come from Infinity. I'll move this issue there, although this will probably end up being a `wontfix` issue for us, since we're going to be ditching Infinity in our new CBOX theme.  

That's a neat hack for quieting error messages! Thanks for that.

**Comment by r-a-y** [comment]
Keep us apprised on the new theme you guys are creating, @JonathanReeve, as I'm sure it will be useful to many people.

**Comment by MrMaz** [comment]
The bleeding edge of the default theme is almost ready for testing. I'm
just finalizing back compat.

Infinity has been significantly overhauled and improved.

Marshall

**Comment by JonathanReeve** [comment]
@r-a-y, for sure. We're just in the very first planning stages right now, but you can track development in the [cbox-mla](http://github.com/mlaa/cbox-mla) repo, on the 3.0 branch (when it's created). There are some preliminary plans [on the wiki](https://github.com/mlaa/cbox-mla/wiki/CBOX-MLA-3.0-Planning) and [in the issue tracker](https://github.com/mlaa/cbox-mla/issues?q=is:open+is:issue+milestone:3.0), too. If you have any ideas for a good development stack for a project like this, feel free to chime in [on that issue](https://github.com/mlaa/cbox-mla/issues/255) or on the wiki!

@MrMaz, good news! Can't wait to test it out.

**Comment by MrMaz** [comment]
Jonathan, the latest theme takes advantage of the bp-legacy templates, so
there are only 3 or 4 templates which needed to be forked. The css was
completely overhauled so 99% of the rules are now scoped, and there are no
more dynamic css files, etc.

**Comment by JonathanReeve** [comment]
Marshall, that sounds exciting! Those were some of the biggest issues I had with the current theme.

**Comment by BoweFrankema** [comment]
We created CBOX/Infinity before pre-processing workflows with Gulp/Grunt and LESS/SASS were being used widely in the WP theme ecosystem. Ideally we'd work towards incorporating these new tools into our workflow in the future because it makes things a lot easier for those who want to roll their own custom child themes.
