### ISSUE TITLE
jQuery Load issue on CBOX Options

### ISSUE THREAD

**Issue by vothsco** [cuny-academic-commons/cbox-theme#216]
CBOX member David Reynolds is unable to access CBOX options unless he sets infinit_dev_mode to true.  He has deactivated all his plugins - but the only thing that gets rid of the javascript errors is setting infinit_dev_mode to true.  He has provided the javascript errors at the bottom of this thread:
http://commonsinabox.org/groups/help-support/forum/topic/cannot-change-default-background-image-in-cbox-1-0-8-infinity-theme/

**Comment by r-a-y** [comment]
See #224.  Should be fixed now.
