### ISSUE TITLE
File Chooser Not Displaying correctly in Internet Explorer

### ISSUE THREAD

**Issue by vothsco** [cuny-academic-commons/cbox-theme#229]
CBOX member Perry Kolb reports that the File Chooser for Forum attachments gets "scrunched" when viewed in IE.  On other browsers it is fine.  He has provided screen shots on this thread:
http://commonsinabox.org/groups/help-support/forum/topic/internet-explorer-issues/

Also, the file chooser for the BP Groups Docs plugin displays similarly - probably is related.  Again, only using Internet Explorer.

**Comment by christianwach** [comment]
I don't see this in my IE versions. Will investigate further when Perry responds with his system details

**Comment by r-a-y** [comment]
I was able to duplicate the issue.  Also tested on FIrefox and Chromium to make sure the changes didn't impede those browsers as well and it looked safe to me :)
