### ISSUE TITLE
Forum tags obscured after clicking one

### ISSUE THREAD

**Issue by vothsco** [cuny-academic-commons/cbox-theme#252]
I noticed a minor issue with forum tags.  If there are forum topic tags, and you click on one, the list is generated correctly, but the tags at the top of the list are almost totally obscured.

**Comment by boonebgorges** [comment]
Thanks for the report, @vothsco. I see a bit of oddness with the styling on the forum tag page, but it doesn't seem to have anything to do with obscuring the *tag list*. Can you provide a screenshot so I can understand more clearly?

**Comment by vothsco** [comment]
![screenshot1](https://cloud.githubusercontent.com/assets/630806/21326214/aa834438-c5f7-11e6-91b8-8d76fc17a77c.png)
![screenshot2](https://cloud.githubusercontent.com/assets/630806/21326215/aa83c7aa-c5f7-11e6-93dc-f7c297b6b32a.png)

**Comment by boonebgorges** [comment]
Gotcha! That's what I was seeing too. Thanks, @vothsco

**Comment by vothsco** [comment]
First screenshot is before I click on the tag.  The second is after clicking.

**Comment by boonebgorges** [comment]
Sorry for the delay on this - it should now be fixed.
