### ISSUE TITLE
Add group member search functionality

### ISSUE THREAD

**Issue by r-a-y** [cuny-academic-commons/cbox-theme#259]
A request was made to backport group member search from the BuddyPress bp-legacy template pack to CBOX Theme.

This functionality should show up when you're on a group's "Members" page:
`example.com/groups/THE-GROUP/members/`

Will try to contain the changes within CBOX Theme, but might require upstream changes to the bp-default theme.

**Comment by r-a-y** [comment]
I only backported the HTML markup, and not the JS commits from bp-legacy because those would require fixes upstream to the bp-default theme.

The members search form works, but doesn't use JS to query, fetch and display the results.  I think that is acceptable for our needs.

CC @boonebgorges just to let you know.

**Comment by boonebgorges** [comment]
excellent, thanks!
