### ISSUE TITLE
Ensure activate.php template is updated for BP 3.0 changes

### ISSUE THREAD

**Issue by r-a-y** [cuny-academic-commons/cbox-theme#260]
In BuddyPress 3.0, the activation template has changed.

Previously, simply loading a URL like `/activate/12345` would activate the account with key `12345`.

BP 3.0 no longer does this.  For CBOX theme, we'll need to mirror the following changeset in order to auto-populate the activation key field:
https://buddypress.trac.wordpress.org/changeset/11766/trunk/src/bp-templates/bp-legacy/buddypress/members/activate.php

**Comment by boonebgorges** [comment]
Once we bump the minimum BP requirement in CBOX, it should be updated at the same time as cbox-theme. So I don't think we need to account for older BP. Does that sound right?

**Comment by r-a-y** [comment]
I was thinking about those that clone and pull `cbox-theme` (or `bp-default) without updating BuddyPress to v3.0 immediately.

In those instances, the activation page would throw a fatal error due to the use of a BP 3.0 function.  Am I overthinking things?

**Comment by boonebgorges** [comment]
Ah, I see. Yeah, I think that's overthinking. Anyone doing weird stuff should know enough to test :)

**Comment by r-a-y** [comment]
Gotcha.  Thanks for sanity check!
