### ISSUE TITLE
php 7.2 deprecated feature

### ISSUE THREAD

**Issue by bdolor** [cuny-academic-commons/cbox-theme#262]
Line 247 throws a PHP deprecated notice in a 7.2 environment: https://github.com/cuny-academic-commons/cbox-theme/blob/master/engine/ICE/base/base.php#L247

reference: https://secure.php.net/manual/en/migration72.deprecated.php#migration72.deprecated.unset-cast

![image](https://user-images.githubusercontent.com/2048170/41069808-5bd9ffdc-69a4-11e8-9807-524c71c4c5db.png)

changing it to `return $value = NULL;` will suffice?

**Comment by boonebgorges** [comment]
Thanks for the ticket. We'll look at this for the next release.

**Comment by r-a-y** [comment]
Thanks for the report, @bdolor.  Should be fixed as of commit b5a0994.
