### ISSUE TITLE
Support selectable profile fields on registration page

### ISSUE THREAD

**Issue by r-a-y** [cuny-academic-commons/cbox-theme#270]
This is a new feature in BuddyPress 8.0.0:
https://bpdevel.wordpress.com/2021/05/06/selectable-xprofile-sign-up-fields-in-8-0-0

Requires a one-line change to our registration template.

**Comment by boonebgorges** [comment]
Thanks for this ticket, @r-a-y. The change requires that we have BP 8.0, but that shouldn't be a problem because of the order in which CBOX upgrades plugins/themes, right? I want to be 100% sure we don't need `function_exists()` checks or whatever.

**Comment by r-a-y** [comment]
> The change requires that we have BP 8.0, but that shouldn't be a problem because of the order in which CBOX upgrades plugins/themes, right? I want to be 100% sure we don't need function_exists() checks or whatever.

I thought about adding in the `function_exists()` check before committing, but decided not to because the change is only applicable to the registration page and should not affect the CBOX upgrade process.

It doesn't hurt to have the `function_exists()` check though and might be good to have for those stuck on older versions of BuddyPress, but decide to manually upgrade the theme through Github. I guess that's a decent reason to add in the check. Going to add it now.
