### ISSUE TITLE
Disabling block widgets

### ISSUE THREAD

**Issue by r-a-y** [cuny-academic-commons/cbox-theme#274]
One of the sites I help to manage encountered an issue with the new Block Widgets functionality in WP 5.8 where all widgets were missing on the homepage. Installing the Classic Widgets plugin brought them back, but there is an easier way to disable block widgets as outlined here: https://make.wordpress.org/core/2021/06/29/block-based-widgets-editor-in-wordpress-5-8/

I'm going to disable block widgets functionality for the CBOX Theme. @boonebgorges, any thoughts here?

**Comment by boonebgorges** [comment]
Yes, that seems like a wise idea.

If we ever have the resources, it may also be worth looking into whether there are specific things that the CBOX widgets are doing that makes them incompatible with the Block Editor. The post you linked, for example, has notes about `is_admin()` - if it's something as simple as that, then it might be worth fixing.

That being said, I don't think we have the ability to research this now, and some of the issues may be upstream or related to separate packages that aren't easily fixed. So let's go ahead and disable in cbox-theme.

**Comment by r-a-y** [comment]
I can confirm that the issue is due to BuddyPress 10.0. If BP 10 is installed, all older BuddyPress widgets are gone unless block widgets are explicitly disabled. This is due to the `bp_core_retain_legacy_widgets()` function: https://buddypress.trac.wordpress.org/browser/tags/10.0.0/src/bp-core/bp-core-widgets.php#L13

I think BuddyPress needs to check all widget sidebars for a BP legacy widget before thinking about disabling. Not sure how easy that is. I'll raise an issue on BP Trac.

**Comment by boonebgorges** [comment]
Yeah, that does seem like a pretty serious problem in BuddyPress. For us to filter `bp_core_retain_legacy_widgets` is no big deal, but for existing sites that all of a sudden see their widgets disappear, it seems pretty bad.

**Comment by r-a-y** [comment]
> I think BuddyPress needs to check all widget sidebars for a BP legacy widget before thinking about disabling. Not sure how easy that is. I'll raise an issue on BP Trac.

This should be fixed in BuddyPress 10.1.0, which was released yesterday. See https://buddypress.trac.wordpress.org/ticket/8625.

Going to close this one.
